# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KPT0whHQ7vFchKQ1-VN51DPabyNtmsOp

# Logistic Regression
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
from google.colab import files  # Import for auto-download in Google Colab

# Load the labeled dataset
file_path = "labeled_dataset.csv"  # Replace with your dataset path
data = pd.read_csv(file_path)

# Separate features and labels
X = data.drop("label", axis=1)  # Features
y = data["label"]               # Labels

# Split the dataset into an 80/20 training and testing split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Logistic Regression Model
logistic_model = LogisticRegression(random_state=42, max_iter=1000)
logistic_model.fit(X_train, y_train)

# Make predictions
y_pred_logistic = logistic_model.predict(X_test)

# Print Evaluation Metrics
print("----- Logistic Regression -----")
print("Classification Report:\n", classification_report(y_test, y_pred_logistic))
print(f"Accuracy: {accuracy_score(y_test, y_pred_logistic) * 100:.2f}%")
print(f"Precision: {precision_score(y_test, y_pred_logistic) * 100:.2f}%")
print(f"Recall: {recall_score(y_test, y_pred_logistic) * 100:.2f}%")
print(f"F1 Score: {f1_score(y_test, y_pred_logistic) * 100:.2f}%")

# Compute Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred_logistic)

# Plot Confusion Matrix
plt.figure(figsize=(3.5, 3))  # IEEE single-column size
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Normal", "Spoof"], yticklabels=["Normal", "Spoof"])
plt.title("Confusion Matrix - Logistic Regression", fontsize=10)
plt.xlabel("Predicted", fontsize=9)
plt.ylabel("Actual", fontsize=9)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.tight_layout()

# Save Confusion Matrix
plt.savefig("confusion_matrix.pdf", format="pdf", bbox_inches="tight")
plt.savefig("confusion_matrix.png", dpi=300, bbox_inches="tight")
plt.show()

# Compute Feature Importance
feature_importance = np.abs(logistic_model.coef_[0])
feature_importance_normalized = feature_importance / feature_importance.sum() * 100

# Create DataFrame for Feature Contribution
feature_contribution_df = pd.DataFrame({
    "Feature": X.columns,
    "Contribution (%)": feature_importance_normalized
}).sort_values(by="Contribution (%)", ascending=False)

# Display Feature Contributions
print("\nFeature Contributions (in %):")
print(feature_contribution_df)

# Plot Feature Contribution
plt.figure(figsize=(3.5, 3))  # IEEE single-column size
plt.barh(feature_contribution_df["Feature"], feature_contribution_df["Contribution (%)"], color="skyblue")
plt.title("Model Specific Feature Contribution - Logistic Regression", fontsize=8)
plt.xlabel("Contribution (%)", fontsize=8)
plt.ylabel("Features", fontsize=8)

# Add Text Labels for Each Bar
for index, value in enumerate(feature_contribution_df["Contribution (%)"]):
    plt.text(value + 0.5, index, f"{value:.1f}%", fontsize=8, va='center')

plt.gca().invert_yaxis()  # Highest contribution at the top
plt.tight_layout()

# Save Feature Contribution Plot
plt.savefig("feature_contribution.pdf", format="pdf", bbox_inches="tight")
plt.savefig("feature_contribution.png", dpi=300, bbox_inches="tight")
plt.show()

# Auto-download images in Google Colab
files.download("confusion_matrix.pdf")
files.download("confusion_matrix.png")
files.download("feature_contribution.pdf")
files.download("feature_contribution.png")

"""# Naive Bayes"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
from google.colab import files  # For auto-download in Google Colab

# Load the labeled dataset
file_path = "labeled_dataset.csv"  # Replace with your dataset path
data = pd.read_csv(file_path)

# Separate features and labels
X = data.drop("label", axis=1)  # Features
y = data["label"]               # Labels

# Split the dataset into an 80/20 training and testing split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Naive Bayes model
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

# Make predictions
y_pred_nb = nb_model.predict(X_test)

# Print Evaluation Metrics
print("----- Naive Bayes -----")
print("Classification Report:\n", classification_report(y_test, y_pred_nb))
print(f"Accuracy: {accuracy_score(y_test, y_pred_nb) * 100:.2f}%")
print(f"Precision: {precision_score(y_test, y_pred_nb) * 100:.2f}%")
print(f"Recall: {recall_score(y_test, y_pred_nb) * 100:.2f}%")
print(f"F1 Score: {f1_score(y_test, y_pred_nb) * 100:.2f}%")

# Compute Confusion Matrix
conf_matrix_nb = confusion_matrix(y_test, y_pred_nb)

# Plot Confusion Matrix
plt.figure(figsize=(3.5, 3))  # IEEE single-column size
sns.heatmap(conf_matrix_nb, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Normal", "Spoof"], yticklabels=["Normal", "Spoof"])
plt.title("Confusion Matrix - Naive Bayes", fontsize=10)
plt.xlabel("Predicted", fontsize=9)
plt.ylabel("Actual", fontsize=9)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.tight_layout()

# Save Confusion Matrix
plt.savefig("confusion_matrix_nb.pdf", format="pdf", bbox_inches="tight")
plt.savefig("confusion_matrix_nb.png", dpi=300, bbox_inches="tight")
plt.show()

# Compute Feature Contribution (Using Gaussian Distribution Parameters)
means = nb_model.theta_  # Mean of features per class
std_devs = np.sqrt(nb_model.var_)  # Standard deviation of features per class
features = X.columns

# Calculate feature contribution percentage (normalized inverse variance)
feature_contribution = (1 / std_devs).sum(axis=0) / (1 / std_devs).sum() * 100

# Create a DataFrame for feature contributions
feature_contribution_df = pd.DataFrame({
    "Feature": features,
    "Contribution (%)": feature_contribution
}).sort_values(by="Contribution (%)", ascending=False)

# Display Feature Contributions
print("\nFeature Contributions (in %):")
print(feature_contribution_df)

# Plot Feature Contribution
plt.figure(figsize=(3.5, 3))  # IEEE single-column size
plt.barh(feature_contribution_df["Feature"], feature_contribution_df["Contribution (%)"], color="skyblue")
plt.title("Model Specifc Feature Contribution - Naive Bayes", fontsize=9)
plt.xlabel("Contribution (%)", fontsize=9)
plt.ylabel("Features", fontsize=9)

# Add Text Labels for Each Bar
for index, value in enumerate(feature_contribution_df["Contribution (%)"]):
    plt.text(value + 0.5, index, f"{value:.1f}%", fontsize=8, va='center')

plt.gca().invert_yaxis()  # Highest contribution at the top
plt.tight_layout()

# Save Feature Contribution Plot
plt.savefig("feature_contribution_nb.pdf", format="pdf", bbox_inches="tight")
plt.savefig("feature_contribution_nb.png", dpi=300, bbox_inches="tight")
plt.show()

# Auto-download images in Google Colab
files.download("confusion_matrix_nb.pdf")
files.download("confusion_matrix_nb.png")
files.download("feature_contribution_nb.pdf")
files.download("feature_contribution_nb.png")

"""# Random Forest"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
from google.colab import files  # For auto-download in Google Colab

# Load the labeled dataset
file_path = "labeled_dataset.csv"  # Replace with your dataset path
data = pd.read_csv(file_path)

# Separate features and labels
X = data.drop("label", axis=1)  # Features
y = data["label"]               # Labels

# Split the dataset into an 80/20 training and testing split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Random Forest Model
rf_model = RandomForestClassifier(random_state=42, n_estimators=100)
rf_model.fit(X_train, y_train)

# Make Predictions
y_pred_rf = rf_model.predict(X_test)

# Print Evaluation Metrics
print("\n----- Random Forest -----")
print("Classification Report:\n", classification_report(y_test, y_pred_rf))
print(f"Accuracy: {accuracy_score(y_test, y_pred_rf) * 100:.2f}%")
print(f"Precision: {precision_score(y_test, y_pred_rf) * 100:.2f}%")
print(f"Recall: {recall_score(y_test, y_pred_rf) * 100:.2f}%")
print(f"F1 Score: {f1_score(y_test, y_pred_rf) * 100:.2f}%")

# Compute Confusion Matrix
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)

# Plot Confusion Matrix
plt.figure(figsize=(3.5, 3))  # IEEE single-column size
sns.heatmap(conf_matrix_rf, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Normal", "Spoof"], yticklabels=["Normal", "Spoof"])
plt.title("Confusion Matrix - Random Forest", fontsize=10)
plt.xlabel("Predicted", fontsize=9)
plt.ylabel("Actual", fontsize=9)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.tight_layout()

# Save Confusion Matrix
plt.savefig("confusion_matrix_rf.pdf", format="pdf", bbox_inches="tight")
plt.savefig("confusion_matrix_rf.png", dpi=300, bbox_inches="tight")
plt.show()

# Compute Feature Importance
feature_importance = rf_model.feature_importances_

# Create DataFrame for Feature Contribution
feature_contribution_df = pd.DataFrame({
    "Feature": X.columns,
    "Contribution (%)": feature_importance * 100
}).sort_values(by="Contribution (%)", ascending=False)

# Display Feature Contributions
print("\nFeature Contributions (in %):")
print(feature_contribution_df)

# Plot Feature Contribution
plt.figure(figsize=(3.5, 3))  # IEEE single-column size
plt.barh(feature_contribution_df["Feature"], feature_contribution_df["Contribution (%)"], color="seagreen")
plt.title("Model Specific Feature Contribution - Random Forest", fontsize=9)
plt.xlabel("Contribution (%)", fontsize=9)
plt.ylabel("Features", fontsize=9)

# Add Text Labels for Each Bar
for index, value in enumerate(feature_contribution_df["Contribution (%)"]):
    plt.text(value + 0.5, index, f"{value:.1f}%", fontsize=8, va='center')

plt.gca().invert_yaxis()  # Highest contribution at the top
plt.tight_layout()

# Save Feature Contribution Plot
plt.savefig("feature_contribution_rf.pdf", format="pdf", bbox_inches="tight")
plt.savefig("feature_contribution_rf.png", dpi=300, bbox_inches="tight")
plt.show()

# Auto-download images in Google Colab
files.download("confusion_matrix_rf.pdf")
files.download("confusion_matrix_rf.png")
files.download("feature_contribution_rf.pdf")
files.download("feature_contribution_rf.png")