# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCHrjfbp7wkLqt8VanQBMegB4edy3wj3

# ROC AUC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve
from google.colab import files  # For auto-download in Google Colab

# Load dataset
file_path = "labeled_dataset.csv"  # Replace with your dataset path
data = pd.read_csv(file_path)
X = data.drop("label", axis=1)
y = data["label"]

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize models
models = {
    "Logistic Regression": LogisticRegression(random_state=42, max_iter=1000),
    "Naive Bayes": GaussianNB(),
    "Random Forest": RandomForestClassifier(random_state=42)
}

# Metrics storage
results = []

# ROC curve data storage
roc_data = {}

# Fit models and calculate metrics
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_pred_prob = model.predict_proba(X_test)[:, 1] if hasattr(model, "predict_proba") else None

    # Metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_pred_prob) if y_pred_prob is not None else "N/A"

    results.append({
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1,
        "ROC AUC": roc_auc
    })

    # Store ROC curve data
    if y_pred_prob is not None:
        fpr, tpr, _ = roc_curve(y_test, y_pred_prob)
        roc_data[model_name] = (fpr, tpr)

# Display results in a table
results_df = pd.DataFrame(results)
print("\nModel Comparison:\n")
print(results_df)

# Plot ROC Curves
plt.figure(figsize=(3.5, 3))  # IEEE single-column size
for model_name, (fpr, tpr) in roc_data.items():
    auc_value = roc_auc_score(y_test, models[model_name].predict_proba(X_test)[:, 1])
    plt.plot(fpr, tpr, label=f"{model_name} (AUC = {auc_value:.2f})")

plt.plot([0, 1], [0, 1], linestyle="--", color="gray")
plt.title("ROC Curve Comparison", fontsize=10)
plt.xlabel("False Positive Rate", fontsize=9)
plt.ylabel("True Positive Rate", fontsize=9)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.legend(fontsize=7)
plt.tight_layout()

# Save ROC Curve
plt.savefig("roc_curve_comparison.pdf", format="pdf", bbox_inches="tight")
plt.savefig("roc_curve_comparison.png", dpi=300, bbox_inches="tight")
plt.show()

# Auto-download images in Google Colab
files.download("roc_curve_comparison.pdf")
files.download("roc_curve_comparison.png")